import streamlit as st
import torch

from PIL import Image
from torchvision import transforms, models
from torch import nn


# -----------------------------
# Configuration
# -----------------------------

MODEL_PATH = "models/skin_cancer_model.pth"

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)


# -----------------------------
# Load model
# -----------------------------

@st.cache_resource
def load_model():

    checkpoint = torch.load(
        MODEL_PATH,
        map_location=DEVICE
    )

    classes = checkpoint["classes"]

    model = models.resnet18(
        weights=None
    )

    num_features = model.fc.in_features

    model.fc = nn.Linear(
        num_features,
        2
    )

    model.load_state_dict(
        checkpoint["model_state_dict"]
    )

    model = model.to(DEVICE)

    model.eval()

    return model, classes


model, classes = load_model()


# -----------------------------
# Preprocessing
# -----------------------------

transform = transforms.Compose([
    transforms.Resize((224, 224)),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


# -----------------------------
# UI
# -----------------------------

st.set_page_config(
    page_title="Swatershwar Skin Cancer AI",
    page_icon="🔬"
)


st.title("🔬 Skin Cancer AI")

st.write(
    "AI-assisted skin lesion classification"
)


st.warning(
    "Research prototype only. "
    "This system is not a medical diagnostic tool."
)


uploaded_file = st.file_uploader(
    "Upload a skin lesion image",
    type=[
        "jpg",
        "jpeg",
        "png"
    ]
)


if uploaded_file:

    image = Image.open(
        uploaded_file
    ).convert("RGB")

    st.image(
        image,
        caption="Uploaded image",
        use_container_width=True
    )


    if st.button("Analyze Image"):

        image_tensor = transform(
            image
        ).unsqueeze(0)

        image_tensor = image_tensor.to(
            DEVICE
        )


        with torch.no_grad():

            outputs = model(
                image_tensor
            )

            probabilities = torch.softmax(
                outputs,
                dim=1
            )


        probabilities = (
            probabilities[0]
            .cpu()
            .numpy()
        )


        prediction_index = probabilities.argmax()

        prediction = classes[
            prediction_index
        ]

        confidence = (
            probabilities[prediction_index]
            * 100
        )


        st.divider()

        st.subheader(
            "AI Analysis"
        )


        st.metric(
            "Prediction",
            prediction
        )


        st.write(
            f"Model confidence: "
            f"**{confidence:.2f}%**"
        )


        st.write("Class probabilities:")


        for i, class_name in enumerate(classes):

            st.progress(
                float(probabilities[i])
            )

            st.write(
                f"{class_name}: "
                f"{probabilities[i] * 100:.2f}%"
            )


        st.info(
            "This result is generated by an "
            "experimental machine-learning model "
            "and must not be used to diagnose or "
            "rule out cancer."
        )